### PR TITLE
Fix env var reference

### PR DESCRIPTION
**Pull request by bjaben**
ZipRunFromDirectory suddenly stopped working for me and the environment variable reference in the powershell command seems to be the issue

### CODE REVIEW

**Comment by bjaben** [comment]
Hi @devlead, did you by any chance have the time to look into this small fix? :)

**Comment by devlead** [comment]
@bjaben not yet, but issue is likely a change in how zip deployments work. They've changed name of setting variables and filename for general availability. I'm working testing and bringing that up to speed.

**Comment by devlead** [comment]
@bjaben version 0.6.0 is now released, could you pleas take it for a spin and see if it sorts the issues you were having.
You can read about the release at:
https://medium.com/@devlead/cake-kudu-client-version-0-6-0-released-cb6435629684

**Comment by bjaben** [comment]
@devlead Thanks for the new release. I'm still having the same issues. I'm using this with Azure Functions v.2 and have a method to return the contents of KuduClientZipRunFromDirectoryVersion.txt. I pass the relative URL (api/CodeVersion) as the relativeValidateUrl but I always get this error back when running my deploy.cake:
Error: One or more errors occurred.
        Deployment failed expected "20180603_071402_c7625f4f0a0c42fcae5ef984kda983d2.zip" got ""

Before I highly expected the env variable to be incorrectly referenced and thus causing the validate URL to be incorrect. Can this be the case?

**Comment by devlead** [comment]
@bjaben ah this might be a function specific thing. Kudu now supports RunFromZip via ZipDeploy if the AppSetting `WEBSITE_RUN_FROM_ZIP` is set to `1`.

This simplifies things a lot as you should just be able to do:
```cake
 #addin nuget:?package=Cake.Kudu.Client

 string  baseUri     = EnvironmentVariable("KUDU_CLIENT_BASEURI"),
         userName    = EnvironmentVariable("KUDU_CLIENT_USERNAME"),
         password    = EnvironmentVariable("KUDU_CLIENT_PASSWORD");

 IKuduClient kuduClient = KuduClient(
     baseUri,
     userName,
     password);

 DirectoryPath sourceDirectoryPath = "./Documentation/";

 kuduClient.ZipDeployDirectory(
     sourceDirectoryPath);
```

and if `WEBSITE_RUN_FROM_ZIP` is set to `1`, then it shouldn't unzip on AppService, but actually run from zip.

**Comment by bjaben** [comment]
ah, so I'll use ZipDeployDirectory from now on, thanks @devlead ! 😄 
Will it return an exception if for some reason the zip file did not get uploaded or the packagename.txt contents could not be changed?

**Comment by devlead** [comment]
Yes it should.

**Comment by bjaben** [comment]
Perfect!
Thanks for you help @devlead 😃
I'll close this PR then.

**Pull request closed without merging**
